### ISSUE TITLE
Alpimaps sets brightness to minimum on startup and I cannot see anything

### ISSUE THREAD

**Issue by nach0** [Akylas/alpimaps#1]
I wanted to try Alpimaps, but every time I open the app the screen goes very dark, as if the brightness was set to the minimum (or even lower?) and it's really hard to see anything. I have managed to tap on some buttons but I don't see any option to change the brightness, so I cannot try the app.

I have tried deleting cache and data, and reinstalling the app, both from F-Droid and github. It keeps happening every single time.

My device is a FairPhone 4 running iodéOS 3.4 (based on Android 12).

**Comment by farfromrefug** [comment]
@nach0 wow actually did not know some people were testing this! Can you tell me which version you installed? I ll try to reproduce

**Comment by nach0** [comment]
Well, yes. I saw a new maps app in F-Droid that could be useful for hikes, so I decided to give it a try.

So far I have tested versions 2.0.0.226 and 2.0.0.227, and had the same problem with both. As additional information, I mentioned that my OS is iodéOS 3.4 (based on Android 12), it is quite close to LineageOS 19, so it is fairly degoogled (has no Google Play services, but has microG). In case this information is useful.

**Comment by farfromrefug** [comment]
@nach0 OK. Thanks! I use los toi son we should get around the same behaviors. I will look into it. 
I should mention that is app.is a bit particular in the sense that it is best used with offline generated data. It can work with offline map,hill shades, contours, hiking routes,  routing, geocoding....
The idea is you can generate those maps yourself so that you never need anything else. 
I ll share the repo where I explain how to generate stuff

**Comment by nach0** [comment]
That sounds great!
I already use Organic Maps and OsmAnd with offline maps. And I am diving into getting gpx files to plan routes and maybe editing them beforehand, so I thought I'd give Alpimaps a try and see how it works for those things. It sounds like it will be a good match :)

**Comment by farfromrefug** [comment]
@nach0 here is it the repo explaining how to generate data https://github.com/Akylas/alpimaps_data_generator
It is not "easy" but doable.
I can also generate for your country if you want. I already have France and Italy but i could generate others.

**Comment by nach0** [comment]
I'm happy to report that with the latest update (2.0.0.228) the bug with the very dark display is gone. Now I'm ready to try the app.

**Comment by farfromrefug** [comment]
@nach0 thanks for reporting this I wanted to tell you :) not sure you still had the app installed :)
