### ISSUE TITLE
Why is AlpiMaps requesting permission to manage all system files?

### ISSUE THREAD

**Issue by whiver** [Akylas/alpimaps#2]
Hi,

Just installed Alpi Maps, and on first launch I got a permission prompt to access and manage all files of every connected storage volume.

Is Alpi Maps really needing such a permission? Why?

See below screenshot (in French):

![Screenshot_20230204-091341](https://user-images.githubusercontent.com/394565/216756743-da31d484-39cb-495b-9ee9-a61bf7bea43b.png)

**Comment by farfromrefug** [comment]
@whiver yes it does. Alpimaps main purpose is to use offline data for map,routing,geocoding,hillshades... And all that data needs space on the sdcard. I could use per file asked permission but it is too tedious and it is much easier this way.
Alpimaps does not do anything else but read sqilte database files using that permission

**Comment by whiver** [comment]
Thank for your answer! Couldn't we either use the app's storage (without permission), or require permissions only on a specific folder if we want to une another folder?

**Comment by farfromrefug** [comment]
@whiver sadly directory permission does not work with carto mobile SDK yet. We havent found the solution.
However that permission does not seem like a big deal to me. The app is 100% open source and you can look at what I do with permission. And I dont intend to go on the appstore.
Tbh I didn't even know alpimaps was on fdroid ;) it was mainly for my and friends use. I ll try to cleanup things if more people start to use it. 
I use it mainly to plan hiking and cycling trips

**Comment by whiver** [comment]
Alright, thanks for your answer @farfromrefug :)
