### ISSUE TITLE
Sentry

### ISSUE THREAD

**Issue by IzzySoft** [Akylas/alpimaps#3]
I just noticed the latest release ships with the Sentry SDK. Could you please clarify how you use it – especially if it is strictly opt-in, or what details are collected automatically without prior confirmation by the user, and what control the user has over what is collected?

No offense meant, but this is something privacy-aware users would like to know in advance :wink: So thanks in advance for letting us know!

**Comment by farfromrefug** [comment]
@IzzySoft fast catch! Was added just to indentify a crash for some users on startup. I dont record stats or performances or anything like that. 
And it will be removed in next version if the crash is fixed. Is that ok with you?

**Comment by IzzySoft** [comment]
> I dont record stats or performances or anything

well, the main question is what leaves the client's system by default – so how does it affect "unaware users". If it's strictly opt-in I'd simply white-list (trusting there's a proper explanation of what information is sent) – this is e.g. the case for ACRA when just used to mail crash reports (popup asking user to send what is shown).

So if users are presented with what will be sent and it's their decision whether it indeed is sent, all is fine (and I can white-list). Otherwise I'd had to raise the `Tracking` flag, even if temporarily (as my updater informed me about the presence of a previously non-present tracking library and no `Tracking` set, it will inform me of `Tracking` set with no more tracking libs present :wink:).

**Comment by farfromrefug** [comment]
@IzzySoft Love what you do! Yes mark it as with `Tracking` for now. I dont mind. Will be removed in the days to come.
Thanks again

**Comment by IzzySoft** [comment]
Thanks! Done that for now (reflected with the next sync around 7 pm UTC). Should the flag not have been removed within 2..3 days of your removing Sentry, feel free to give me a ping – otherwise, this issue can then be closed.
