### ISSUE TITLE
OpenStreetMap attribution

### ISSUE THREAD

**Issue by ghost** [Akylas/alpimaps#4]
Hi!
You're using OpenStreetMap tiles—thank you!
But you forgot the required attribution « OpenStreetMap ». See https://wiki.osmfoundation.org/wiki/Licence/Attribution_Guidelines

Thanks by advance!

**Comment by farfromrefug** [comment]
@AntoninDelFabbro you are 100% right. Until now that app was only for me. Now that it is on fdroid I need to add it

**Comment by farfromrefug** [comment]
@AntoninDelFabbro should be fixed in the latest version. on "i" button should be present on the map when needed.
Let me know if that is ok with you
