### ISSUE TITLE
App not asking for storage permission on startup

### ISSUE THREAD

**Issue by davidlesicnik** [Akylas/alpimaps#7]
After a fresh install on my Pixel 7, when I open the app I instantly get the below message. After that the map itself (obviously) doesnt load.

![Screenshot_20230301-093653](https://user-images.githubusercontent.com/37893600/222087203-87dd065e-931e-4e0d-8671-b109aa646b4a.png)

If i click Ok and then tap the location icon it brings up the permission prompt.

Also UI elements seem to conflict with the status bar. Search on the main screen and the app bar in the settings.

**Comment by farfromrefug** [comment]
@davidlesicnik thanks for the report. All should be fixed in https://github.com/Akylas/alpimaps/releases/tag/android%2Fgithub%2F2.0.1%2F233 which should be released tomorrow on IzzyOnDroid
